/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufes.inf.nemo.frameweb.vp.view;

/**
 *
 * @author FULLM
 */
public class FileTypeEdit extends javax.swing.JPanel {

    /**
     * Creates new form FileTypeEdit
     */
    public FileTypeEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        templateLabel = new javax.swing.JLabel();
        templateFieldText = new javax.swing.JTextField();
        extensionLabel = new javax.swing.JLabel();
        extensionTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0};
        setLayout(layout);

        templateLabel.setText("Template");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(templateLabel, gridBagConstraints);

        templateFieldText.setPreferredSize(new java.awt.Dimension(200, 22));
        templateFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateFieldTextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(templateFieldText, gridBagConstraints);

        extensionLabel.setText("Extension");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(extensionLabel, gridBagConstraints);

        extensionTextField.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(extensionTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void templateFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templateFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_templateFieldTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel extensionLabel;
    private javax.swing.JTextField extensionTextField;
    private javax.swing.JTextField templateFieldText;
    private javax.swing.JLabel templateLabel;
    // End of variables declaration//GEN-END:variables
}
