spring:
  controller:
    extension: .java
    template: ControllerClassTemplate.ftl
  dao:
    extension: .java
    template: DaoClassTemplate.ftl
  daoInterface:
    extension: .java
    template: DaoInterfaceTemplate.ftl
  description: Default Template for Spring projects
  embeddable:
    extension: .java
    template: EmbeddableClassTemplate.ftl
  entity:
    extension: .java
    template: EntityClassTemplate.ftl
  enumeration:
    extension: .java
    template: EnumerationClassTemplate.ftl
  mappedSuperclass:
    extension: .java
    template: MappedSuperclassTemplate.ftl
  name: spring
  outputPath: /spring/{projectName}
  service:
    extension: .java
    template: ServiceClassTemplate.ftl
  serviceInterface:
    extension: .java
    template: ServiceInterfaceTemplate.ftl
  templatePath: templates/spring
  transientClass:
    extension: .java
    template: PojoTemplate.ftl


jbutler:
  controller:
    extension: .java
    template: ControllerClassTemplate.ftl
  dao:
    extension: .java
    template: DaoClassTemplate.ftl
  daoInterface:
    extension: .java
    template: DaoInterfaceTemplate.ftl
  description: Default Template for JButler
  embeddable:
    extension: .java
    template: EmbeddableClassTemplate.ftl
  entity:
    extension: .java
    template: EntityClassTemplate.ftl
  enumeration:
    extension: .java
    template: EnumerationClassTemplate.ftl
  mappedSuperclass:
    extension: .java
    template: MappedSuperclassTemplate.ftl
  name: jbutler
  outputPath: /jbutler/{projectName}
  service:
    extension: .java
    template: ServiceClassTemplate.ftl
  serviceInterface:
    extension: .java
    template: ServiceInterfaceTemplate.ftl
  templatePath: /templates/jbutler
  transientClass:
    extension: .java
    template: PojoTemplate.ftl
