package br.ufes.inf.nemo.frameweb.vp.view;

import br.ufes.inf.nemo.frameweb.vp.FrameWebPlugin;
import br.ufes.inf.nemo.frameweb.vp.utils.TemplateUtils;
import br.ufes.inf.nemo.vpzy.engine.models.base.TemplateOption;
import br.ufes.inf.nemo.vpzy.logging.Logger;
import br.ufes.inf.nemo.vpzy.utils.ProjectManagerUtils;
import br.ufes.inf.nemo.vpzy.utils.ViewManagerUtils;
import com.vp.plugin.VPPluginInfo;
import com.vp.plugin.view.IDialog;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Collection;
import java.util.logging.Level;

/**
 *
 * @author <a href="https://github.com/Gianluca-Mantovaneli">Gianluca Mantovaneli</a>
 */
public class GenerateCodePanel extends javax.swing.JPanel {

    String defaultOutputPath = System.getProperty("user.home") + File.separator + "frameweb-generated-code";

    private IDialog containerDialog;

    /**
     * Creates new form GenerateCodePanel
     */
    public GenerateCodePanel() {
        initComponents();
        templateSelecter.setModel(getTemplateOptions());
        this.setAlignmentY(Component.CENTER_ALIGNMENT);
        this.outputSelecter.setText(defaultOutputPath);
    }

    /**
     * Gets the container dialog of this panel, which is used to show the panel in a dialog and can be used to close it.
     * @param containerDialog
     */
    public void setContainerDialog(final IDialog containerDialog) {
        this.containerDialog = containerDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        templateSelecter = new javax.swing.JComboBox<>();
        outputSelecter = new javax.swing.JTextField();
        choosePathButton = new javax.swing.JButton();
        addTemplateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generateCodeButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Generate Code"));
        setPreferredSize(new java.awt.Dimension(512, 256));

        templateSelecter.setModel(new DefaultComboBoxModel<TemplateOption>());
        templateSelecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        templateSelecter.addActionListener(this::templateSelecterActionPerformed);

        outputSelecter.setText("Output Path");
        outputSelecter.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        choosePathButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        choosePathButton.setText("...");
        choosePathButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choosePathButton.addActionListener(this::choosePathButtonActionPerformed);

        addTemplateButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addTemplateButton.setText("+");
        addTemplateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTemplateButton.addActionListener(this::addTemplateButtonActionPerformed);

        jLabel1.setText("Template");

        jLabel2.setText("Output");

        generateCodeButton.setText("Generate");
        generateCodeButton.addActionListener(this::generateCodeButtonActionPerformed);
        generateCodeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(outputSelecter)
                                        .addComponent(templateSelecter, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(choosePathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addTemplateButton))
                                .addContainerGap(42, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateCodeButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(templateSelecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7)
                                                .addComponent(outputSelecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(addTemplateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(choosePathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(generateCodeButton)
                                .addContainerGap())
        );
    }// </editor-fold>

    public static DefaultComboBoxModel<TemplateOption> getTemplateOptions() {
        final br.ufes.inf.nemo.vpzy.managers.JsonConfigurationManager manager = FrameWebPlugin.instance().getGenerateCodeConfigManager();

        final Collection <TemplateOption> values = FrameWebPlugin.instance().getGenerateCodeConfigManager().getOptions().values();

        if (values.isEmpty()) {
            return new DefaultComboBoxModel<>(new TemplateOption[0]);
        }
        return new DefaultComboBoxModel<>(values.toArray(new TemplateOption[0]));
    }

    private void addTemplateButtonActionPerformed(java.awt.event.ActionEvent evt) {

        String pluginID = "br.ufes.inf.nemo.frameweb.vp";
        VPPluginInfo pluginInfo = com.vp.plugin.ApplicationManager.instance().getPluginInfo(pluginID);

        if (pluginInfo == null) {
            Logger.log(Level.SEVERE, "Plugin not found: " + pluginID);
        }

        File templatesDir = new File(pluginInfo.getPluginDir(), "templates");

        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Zip files", "zip"));

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File zipFile = chooser.getSelectedFile();
            try {
                unzip(zipFile, templatesDir);
                JOptionPane.showMessageDialog(this, "Template adicionado com sucesso!");
                Logger.log(Level.INFO, "Template adicionado com sucesso!");
                FrameWebPlugin.instance().getGenerateCodeConfigManager().load();
                templateSelecter.setModel(getTemplateOptions());

            }catch (IOException e) {
                Logger.log(Level.SEVERE, "Error while adding template", e);
            }
        }

    }

    private void templateSelecterActionPerformed(java.awt.event.ActionEvent evt) {
        // No action needed for now.
    }

    private void choosePathButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValor = chooser.showOpenDialog(this);
        if (returnValor == JFileChooser.APPROVE_OPTION)
            outputSelecter.setText(chooser.getSelectedFile().getAbsolutePath());
    }

    private void generateCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            final TemplateOption selectedItem = (TemplateOption) templateSelecter.getSelectedItem();

            if (selectedItem == null || selectedItem.getName() == null) {
                ViewManagerUtils.showMessageDialog("Please select a template option", "Error",
                        ViewManagerUtils.ERROR_MESSAGE);
                return;
            }

            TemplateUtils.generateCode(selectedItem);
            ViewManagerUtils.showMessageDialog("Code generated successfully", "Success",
                    ViewManagerUtils.INFORMATION_MESSAGE);

            final File file = new File(defaultOutputPath);
            final Desktop desktop = Desktop.getDesktop();
            desktop.open(file);

        } catch (Exception e) {
            Logger.log(Level.SEVERE, "Error while generating code", e);
            ViewManagerUtils.showMessageDialog("Error while generating code", "Error", ViewManagerUtils.ERROR_MESSAGE);
        }
    }

    /**
     * Unzips a zip file to a destination directory.
     * @param zipFile
     * @param destDir
     * @throws IOException
     */
    private void unzip(File zipFile, File destDir) throws IOException {
        if (!destDir.exists()) destDir.mkdirs();
        try (java.util.zip.ZipInputStream zis = new java.util.zip.ZipInputStream(new java.io.FileInputStream(zipFile))) {
            java.util.zip.ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                File newFile = new File(destDir, entry.getName());
                if (entry.isDirectory()) {
                    newFile.mkdirs();
                } else {
                    newFile.getParentFile().mkdirs();
                    try (java.io.FileOutputStream fos = new java.io.FileOutputStream(newFile)) {
                        byte[] buffer = new byte[1024];
                        int len;
                        while ((len = zis.read(buffer)) > 0) {
                            fos.write(buffer, 0, len);
                        }
                    }
                }
            }
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton addTemplateButton;
    private javax.swing.JButton choosePathButton;
    private javax.swing.JButton generateCodeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField outputSelecter;
    private javax.swing.JComboBox<TemplateOption> templateSelecter;


    // End of variables declaration
}

