package br.ufes.inf.nemo.frameweb.vp.view;

import br.ufes.inf.nemo.frameweb.vp.FrameWebPlugin;
import br.ufes.inf.nemo.frameweb.vp.utils.TemplateUtils;
import br.ufes.inf.nemo.vpzy.engine.models.base.TemplateOption;
import br.ufes.inf.nemo.vpzy.logging.Logger;
import br.ufes.inf.nemo.vpzy.utils.ViewManagerUtils;
import com.vp.plugin.VPPluginInfo;
import com.vp.plugin.view.IDialog;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.Collection;
import java.util.logging.Level;

public class GenerateCodePanel extends javax.swing.JPanel {

    String defaultOutputPath = System.getProperty("user.home") + File.separator + "frameweb-generated-code";
    private IDialog containerDialog;

    /**
     * Creates new form GenerateCodePanel
     */
    public GenerateCodePanel() {
        initComponents();
        templateSelecter.setModel(getTemplateOptions());
        this.outputSelecter.setText(defaultOutputPath);
    }

    /**
     * Gets the container dialog of this panel, which is used to show the panel in a dialog and can be used to close it.
     * @param containerDialog
     */
    public void setContainerDialog(final IDialog containerDialog) {
        this.containerDialog = containerDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTemplateButton = new javax.swing.JButton();
        outputSelecter = new javax.swing.JButton();
        outputTextField = new javax.swing.JTextField();
        templateSelecter = new javax.swing.JComboBox<>();
        generateCodeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Generate Code"));

        templateSelecter.setCursor(new java.awt.Cursor(Cursor.HAND_CURSOR));
        templateSelecter.setToolTipText("Select a Template");

        addTemplateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addTemplateButton.setText("+");
        addTemplateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTemplateButton.setToolTipText("Add a new template from .zip File or directory");
        addTemplateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTemplateButtonActionPerformed(evt);
            }
        });

        outputSelecter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outputSelecter.setText("...");
        outputSelecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        outputSelecter.setToolTipText("Choose the output directory for generated code");
        outputSelecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePathButtonActionPerformed(evt);
            }
        });

        outputTextField.setText(defaultOutputPath);

        generateCodeButton.setText("Generate");
        generateCodeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateCodeButton.setToolTipText("Generate code from the selected template");
        generateCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateCodeButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Template :");

        jLabel2.setText("OutPut :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(templateSelecter, 0, 288, Short.MAX_VALUE)
                                                        .addComponent(outputTextField))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addTemplateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(outputSelecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(generateCodeButton)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addTemplateButton)
                                        .addComponent(templateSelecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outputSelecter)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(generateCodeButton)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public static DefaultComboBoxModel<TemplateOption> getTemplateOptions() {
        final br.ufes.inf.nemo.vpzy.managers.JsonConfigurationManager manager = FrameWebPlugin.instance().getGenerateCodeConfigManager();

        final Collection <TemplateOption> values = FrameWebPlugin.instance().getGenerateCodeConfigManager().getOptions().values();

        if (values.isEmpty()) {
            return new DefaultComboBoxModel<>(new TemplateOption[0]);
        }
        return new DefaultComboBoxModel<>(values.toArray(new TemplateOption[0]));
    }

    /**
     * Handles the action of adding a new template. It opens a file chooser to select either a .zip file or a directory containing the template, and then processes it accordingly.
     * @param evt
     */
    private void addTemplateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String pluginID = "br.ufes.inf.nemo.frameweb.vp";
        VPPluginInfo pluginInfo = com.vp.plugin.ApplicationManager.instance().getPluginInfo(pluginID);

        if (pluginInfo == null) {
            Logger.log(Level.SEVERE, "Plugin not found: " + pluginID);
            return;
        }

        File templatesDir = new File(pluginInfo.getPluginDir(), "templates");

        JFileChooser chooser = new JFileChooser();
        // Permite a seleção de arquivos e diretórios
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        // Adiciona um filtro para arquivos .zip, mas também permite ver diretórios
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Zip files or Directories", "zip"));
        chooser.setAcceptAllFileFilterUsed(false); // Opcional: remove o filtro "All Files"

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            try {
                if (selectedFile.isDirectory()) {
                    // Se um diretório for selecionado, copia seu conteúdo
                    File destDir = new File(templatesDir, selectedFile.getName());
                    copyDirectory(selectedFile, destDir);
                } else if (selectedFile.getName().toLowerCase().endsWith(".zip")) {
                    // Se um arquivo .zip for selecionado, descompacta
                    unzip(selectedFile, templatesDir);
                } else {
                    // Caso o arquivo não seja um .zip
                    JOptionPane.showMessageDialog(this, "Por favor, selecione um arquivo .zip ou um diretório.", "Tipo de arquivo inválido", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Template adicionado com sucesso!");
                Logger.log(Level.INFO, "Template adicionado com sucesso!");
                FrameWebPlugin.instance().getGenerateCodeConfigManager().load();
                templateSelecter.setModel(getTemplateOptions());

            } catch (IOException e) {
                Logger.log(Level.SEVERE, "Erro ao adicionar template", e);
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao adicionar o template.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void templateSelecterActionPerformed(java.awt.event.ActionEvent evt) {
        // No action needed for now.
    }

    private void choosePathButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValor = chooser.showOpenDialog(this);
        if (returnValor == JFileChooser.APPROVE_OPTION) {
            outputTextField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }

    private void generateCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            final TemplateOption selectedItem = (TemplateOption) templateSelecter.getSelectedItem();
            String project = com.vp.plugin.ApplicationManager.instance().getProjectManager().getProject().getName();
            String outputDir = outputTextField.getText() + File.separator + project;

            if (selectedItem == null || selectedItem.getName() == null) {
                ViewManagerUtils.showMessageDialog("Please select a template option", "Error",
                        ViewManagerUtils.ERROR_MESSAGE);
                return;
            }

            TemplateUtils.generateCode(selectedItem, outputDir);
            ViewManagerUtils.showMessageDialog("Code generated successfully", "Success",
                    ViewManagerUtils.INFORMATION_MESSAGE);

            final File file = new  File(outputDir);
            final Desktop desktop = Desktop.getDesktop();
            desktop.open(file);

        } catch (Exception e) {
            Logger.log(Level.SEVERE, "Error while generating code", e);
            ViewManagerUtils.showMessageDialog("Error while generating code", "Error", ViewManagerUtils.ERROR_MESSAGE);
        }
    }

    /**
     * Unzips a zip file to a destination directory.
     * @param zipFile
     * @param destDir
     * @throws IOException
     */
    private void unzip(File zipFile, File destDir) throws IOException {
        if (!destDir.exists()) destDir.mkdirs();
        try (java.util.zip.ZipInputStream zis = new java.util.zip.ZipInputStream(new java.io.FileInputStream(zipFile))) {
            java.util.zip.ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                File newFile = new File(destDir, entry.getName());
                if (entry.isDirectory()) {
                    newFile.mkdirs();
                } else {
                    newFile.getParentFile().mkdirs();
                    try (java.io.FileOutputStream fos = new java.io.FileOutputStream(newFile)) {
                        byte[] buffer = new byte[1024];
                        int len;
                        while ((len = zis.read(buffer)) > 0) {
                            fos.write(buffer, 0, len);
                        }
                    }
                }
            }
        }
    }

    /**
     * Copies a source directory to a destination directory recursively.
     * @param source      The source directory.
     * @param destination The destination directory.
     * @throws IOException if an I/O error occurs.
     */
    private void copyDirectory(File source, File destination) throws IOException {
        if (source.isDirectory()) {
            if (!destination.exists()) {
                destination.mkdir();
            }

            String[] files = source.list();
            if (files != null) {
                for (String file : files) {
                    File srcFile = new File(source, file);
                    File destFile = new File(destination, file);
                    copyDirectory(srcFile, destFile);
                }
            }
        } else {
            Files.copy(source.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTemplateButton;
    private javax.swing.JButton generateCodeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField outputTextField;
    private javax.swing.JButton outputSelecter;
    private javax.swing.JComboBox<TemplateOption> templateSelecter;
    // End of variables declaration//GEN-END:variables
}