/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufes.inf.nemo.frameweb.vp.view;

import br.ufes.inf.nemo.frameweb.vp.FrameWebPlugin;
import br.ufes.inf.nemo.frameweb.vp.controllers.AddFrameWebDependencyToClassContextController;
import br.ufes.inf.nemo.frameweb.vp.model.FrameWebClass;
import br.ufes.inf.nemo.vpzy.logging.Logger;
import com.vp.plugin.view.IDialog;

import java.util.List;
import java.util.logging.Level;

/**
 *
 * @author gabriel
 */
public class SelectClassPanel extends javax.swing.JPanel {
    /** The dialog to which this panel serves as contents. */
    private IDialog containerDialog;
    private AddFrameWebDependencyToClassContextController controller;
    /**
     * Creates new form SelectClassPanel
     */
    public SelectClassPanel(AddFrameWebDependencyToClassContextController controller) {
        this.controller = controller;
        initComponents();
    }

    public void setContainerDialog(IDialog containerDialog) {
        this.containerDialog = containerDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classListScrollPane = new javax.swing.JScrollPane();
        classList = new javax.swing.JList<>();
        classListLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        if(controller.getFrameWebClassSelected() == FrameWebClass.SERVICE_CLASS) {
            classList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = controller.getDaoClassesMap().keySet().toArray(new String[0]);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            classListLabel.setText("Select the DAO classes:");
        }
        else if(controller.getFrameWebClassSelected() == FrameWebClass.SERVICE_INTERFACE) {
            classList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = controller.getControllerClassesMap().keySet().toArray(new String[0]);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            classListLabel.setText("Select the Controller classes:");
        }
        classListScrollPane.setViewportView(classList);


        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classListScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(classListLabel)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(classListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        containerDialog.close();
        FrameWebPlugin.instance().setSelectClassDialogOpen(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        List<String> selectedClassesNames = classList.getSelectedValuesList();
        if(selectedClassesNames.isEmpty()){
            Logger.log(Level.INFO, "No class was selected.");
            containerDialog.close();
            FrameWebPlugin.instance().setSelectClassDialogOpen(false);
            return;
        }

        this.controller.addDependencyToSelectedDAO(selectedClassesNames);

        containerDialog.close();
        FrameWebPlugin.instance().setSelectClassDialogOpen(false);
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList<String> classList;
    private javax.swing.JLabel classListLabel;
    private javax.swing.JScrollPane classListScrollPane;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
