/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufes.inf.nemo.frameweb.vp.view;

import br.ufes.inf.nemo.frameweb.vp.FrameWebPlugin;
import br.ufes.inf.nemo.frameweb.vp.controllers.AddFrameWebDependencyToClassContextController;
import br.ufes.inf.nemo.vpzy.logging.Logger;
import com.vp.plugin.model.IClass;
import com.vp.plugin.view.IDialog;

import java.util.List;
import java.util.Map;
import java.util.logging.Level;

/**
 *
 * @author gabriel
 */
public class SelectDAOPanel extends javax.swing.JPanel {
    /** The dialog to which this panel serves as contents. */
    private IDialog containerDialog;
    private AddFrameWebDependencyToClassContextController controller;
    /**
     * Creates new form SelectDAOPanel
     */
    public SelectDAOPanel(AddFrameWebDependencyToClassContextController controller) {
        this.controller = controller;
        initComponents();
    }

    public void setContainerDialog(IDialog containerDialog) {
        this.containerDialog = containerDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daoListScrollPane = new javax.swing.JScrollPane();
        daoList = new javax.swing.JList<>();
        daoListLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();


        daoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = controller.getDaoClassesMap().keySet().toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        daoListScrollPane.setViewportView(daoList);

        daoListLabel.setText("Select the DAO classes:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daoListScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(daoListLabel)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(daoListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daoListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        containerDialog.close();
        FrameWebPlugin.instance().setSelectDAODialogOpen(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        List<String> selectedDAONames = daoList.getSelectedValuesList();
        if(selectedDAONames.isEmpty()){
            Logger.log(Level.INFO, "No DAO class has been selected.");
            containerDialog.close();
            FrameWebPlugin.instance().setSelectDAODialogOpen(false);
            return;
        }
        this.controller.addDependencyToSelectedDAO(selectedDAONames);

        containerDialog.close();
        FrameWebPlugin.instance().setSelectDAODialogOpen(false);
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList<String> daoList;
    private javax.swing.JLabel daoListLabel;
    private javax.swing.JScrollPane daoListScrollPane;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
