<#-- ATTRIBUTES FOR THE CLASS -->
<#macro generate_attributes attributes>
    <#list attributes as attribute>
        <#if attribute.null>@NotNull</#if>
        <#if (attribute.size > 0)>@Size(max = ${attribute.size})</#if>
        <#if attribute.dateTimePrecision?has_content>@Temporal(TemporalType.${attribute.dateTimePrecision?upper_case})</#if>
        ${attribute.visibility.name} ${attribute.type.name} ${attribute.name};
        /** TODO: generated by FrameWeb. Should be documented. ${attribute.dateTimePrecision!""} */
    </#list>
</#macro>
