<#macro generate_list associations className>

    <#list associations as association>
        <#assign sourceToTargetCardinality = association.SourceToTargetCardinality>
        <#assign targetToSourceCardinality = association.TargetToSourceCardinality>
        <#assign sourceTypeName = association.SourceMember.Type.Name>
        <#assign targetTypeName = association.TargetMember.Type.Name>
        <#assign sourceName = association.SourceMember.Name>
        <#assign targetName = association.TargetMember.Name>
        <#assign collection = association.Collection?cap_first>
        <#if sourceTypeName == className && targetTypeName == className >
            <#if sourceToTargetCardinality == "OneToMany" || sourceToTargetCardinality == "ManyToOne">
                /** TODO: generated by FrameWeb. Should be documented. */
                @ManyToOne
                public ${sourceTypeName} ${sourceName};
                /** TODO: generated by FrameWeb. Should be documented. */
                @OneToMany(mappedBy="${sourceName}")
                public ${collection}<${targetTypeName}> ${targetName};
            <#elseif sourceToTargetCardinality == "OneToOne">
                /** TODO: generated by FrameWeb. Should be documented. */
                @OneToOne
                private ${sourceTypeName} ${sourceName};
                /** TODO: generated by FrameWeb. Should be documented. */
                @OneToOne(mappedBy="${sourceName}")
                private ${targetTypeName} ${targetName};
            <#elseif sourceToTargetCardinality == "ManyToMany">
                /** TODO: generated by FrameWeb. Should be documented. */
                @ManyToMany
                private ${collection}<${sourceTypeName}> ${sourceName};
                /** TODO: generated by FrameWeb. Should be documented. */
                @ManyToMany(mappedBy="${sourceName}")
                private ${collection}<${targetTypeName}> ${targetName};
            </#if>
        </#if>
    </#list>

</#macro>

