<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
<#import "InterfaceGeneralizationTemplate.ftl" as generalization>
<#assign defaultGeneralization = "JpaRepository<${clazz.name?replace('Repository', '')}>">
package ${pack.name};

import org.springframework.data.jpa.repository.JpaRepository;

/** TODO: generated by FrameWeb. Should be documented. */
public interface ${clazz.name} <@generalization.generate_generalization generalization=clazz.generalization defaultGeneralization=defaultGeneralization/> {


<#-- METHODS -->
<@method.generate_methods methods=methods/>

}
