<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
package ${package.name};

import org.springframework.data.jpa.repository.JpaRepository;

/** TODO: generated by FrameWeb. Should be documented. */
public interface ${class.name} extends JpaRepository<${class.name?replace('Repository', '')}, Long> {

<#-- METHODS -->
<@method.generate_methods methods=methods/>

}
