<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
<#import "InterfaceGeneralizationTemplate.ftl" as generalization>
<#assign defaultGeneralization = "">
<#assign domainClassName = class.name?replace('Service', '') >
<#assign domainClassNameCamelCase = domainClassName?uncap_first>
package ${package.name};


/** TODO: generated by FrameWeb. Should be documented. */
public interface ${class.name} <@generalization.generate_generalization generalization=class.generalization defaultGeneralization=defaultGeneralization/> {


<#-- METHODS -->
<@method.generate_methods methods=methods/>



public Optional<${domainClassName}> find${domainClassName}ById(Long id);
public List<${domainClassName}> findAll${domainClassName}s();
public ${domainClassName} save${domainClassName}(${domainClassName} ${domainClassNameCamelCase});
public void delete${domainClassName}(${domainClassName} ${domainClassNameCamelCase});

}
