<#ftl strip_whitespace=true>
<#-- ATTRIBUTES FOR THE CLASS -->
<#macro generate_attributes attributes>
    <#list attributes as attribute>
        /** TODO: generated by FrameWeb. Should be documented. */
        <#if attribute.id>@Id</#if>
        <#if attribute.embedded>@Embedded</#if>
        <#if attribute.lob>@Lob</#if>
        <#if attribute.version>@Version</#if>
        <#if attribute.notNull>@NotNull</#if>
        <#if (attribute.size > 0)>@Size(max = ${attribute.size})</#if>
        <#if attribute.dateTimePrecision?has_content>@Temporal(TemporalType.${attribute.dateTimePrecision?upper_case})</#if>
        <#if attribute.transient>@Transient</#if>
        <#if attribute.column?has_content>@Column(name = "${attribute.column}")</#if>
        ${attribute.visibility} ${attribute.type} ${attribute.name};
    </#list>
</#macro>
