<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
package ${package.name};

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ${class.name} extends BaseDAO<${class.name?replace('DAO', '')}> {
<#-- METHODS -->
<@method.generate_methods methods=methods/>
}
