<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
<#import "InterfaceGeneralizationTemplate.ftl" as generalization>
<#assign defaultGeneralization = "BaseDAO<${class.name?replace('DAO', '')}>">
package ${package.name};

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ${class.name} <@generalization.generate_generalization generalization=class.generalization defaultGeneralization=defaultGeneralization/> {
<#-- METHODS -->
<@method.generate_methods methods=methods/>
}
