<#ftl strip_whitespace=true>
<#import "AttributeTemplate.ftl" as attr>
<#import "AttributeGetterSetterTemplate.ftl" as attrgs>
<#import "AssociationTemplate.ftl" as assoc>
<#import "AssociationGetterSetterTemplate.ftl" as assocgs>
<#import "MethodTemplate.ftl" as method>
<#import "ClassGeneralizationTemplate.ftl" as generalization>
<#import "ClassRealizationTemplate.ftl" as realizations>
<#import "EntityGeneralizationStereotype.ftl" as generalization_stereotype>
<#assign defaultGeneralization = "PersistentObjectSupport">
<#assign defaultRealization = "Comparable<${class.name}>">
package ${package.name};


import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

<#--Start of class-->
/** TODO: generated by FrameWeb. Should be documented. */
@Entity
<@generalization_stereotype.generate_generalization_stereotype stereotype=class.inheritanceStereotype/>
public class ${class.name} <@generalization.generate_generalization generalization=class.generalization defaultGeneralization=defaultGeneralization/>  <@realizations.generate_realization realizations=class.realizations defaultRealization=defaultRealization/> {
/** Serialization id. */
private static final long serialVersionUID = 1L;

<#-- ASSOCIATIONS -->
<@assoc.generate_associations associations=associations className=class.name/>

<#-- ATTRIBUTES -->
<@attr.generate_attributes attributes=attributes/>


<#-- METHODS -->
<@method.generate_methods methods=methods/>

// region Boilerplate Code
<#-- GETTERS AND SETTERS ASSOCIATIONS -->
<@assocgs.generate_getter_setter_associations associations=associations className=class.name/>

<#-- GETTERS AND SETTERS ATTRIBUTES -->
<@attrgs.generate_getter_setter_attributes attributes=attributes/>
// endregion


<#--end of class-->
}
