<#ftl strip_whitespace=true>
<#import "../utils/AttributeTemplate.ftl" as attr>
<#import "../utils/AttributeGetterSetterTemplate.ftl" as attrgs>
<#import "../utils/AssociationTemplate.ftl" as assoc>
<#import "../utils/AssociationGetterSetterTemplate.ftl" as assocgs>


package ${package.name};


import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

<#--Start of class-->
/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class ${class.name} extends PersistentObjectSupport implements Comparable<${class.name}>{
    /** Serialization id. */
    private static final long serialVersionUID = 1L;

<#-- ASSOCIATIONS -->
<@assoc.generate_associations associations=associations className=class.name/>

<#-- ATTRIBUTES -->
<@attr.generate_attributes attributes=attributes/>

<#-- GETTERS AND SETTERS ASSOCIATIONS -->
<@assocgs.generate_getter_setter_associations associations=associations className=class.name/>

<#-- GETTERS AND SETTERS ATTRIBUTES -->
<@attrgs.generate_getter_setter_attributes attributes=attributes/>


<#--end of class-->
}
