<#ftl strip_whitespace=true>
package ${pack.name};

/** TODO: generated by FrameWeb. Should be documented. */
public enum ${clazz.name} {
<#list attributes as attribute>
${attribute.name}<#if attribute_has_next>,</#if>
</#list>;
}
