<#ftl strip_whitespace=true>
<#-- ATTRIBUTES FOR THE CLASS -->
<#macro generate_attributes attributes>
    <#list attributes as attribute>
        /** TODO: generated by FrameWeb. Should be documented. */
        ${attribute.visibility} ${attribute.type} ${attribute.name};
    </#list>
</#macro>
