<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
<#import "InterfaceGeneralizationTemplate.ftl" as generalization>
<#assign defaultGeneralization = "">
package ${pack.name};


/** TODO: generated by FrameWeb. Should be documented. */
public interface ${clazz.name} <@generalization.generate_generalization generalization=clazz.generalization defaultGeneralization=defaultGeneralization/> {


<#-- METHODS -->
<@method.generate_methods methods=methods/>


}
