<#ftl strip_whitespace=true>
<#import "MethodInterfaceTemplate.ftl" as method>
<#import "InterfaceGeneralizationTemplate.ftl" as generalization>
<#assign defaultGeneralization = "">
package ${package.name};


/** TODO: generated by FrameWeb. Should be documented. */
public interface ${class.name} <@generalization.generate_generalization generalization=class.generalization defaultGeneralization=defaultGeneralization/> {


<#-- METHODS -->
<@method.generate_methods methods=methods/>


}
